# Machine Learning Zoomcamp


## 1.7 Introduction to NumPy


Plan:

* Creating arrays
* Multi-dimensional arrays
* Randomly generated arrays
* Element-wise operations
    * Comparison operations
    * Logical operations
* Summarizing operations

In [94]:
import numpy as np

In [95]:
np

<module 'numpy' from '/usr/local/python/3.12.1/lib/python3.12/site-packages/numpy/__init__.py'>

## Creating arrays


In [96]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [97]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [98]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [99]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [100]:
a[2] = 10
a

array([ 1,  2, 10,  4,  5])

In [101]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [102]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Multi-dimensional arrays


In [103]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [104]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])

In [105]:
n[0,1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [106]:
n [2] = [1,1,1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [107]:
n[:,2] = [0,1,2]
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

## Randomly generated arrays


In [108]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [109]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [110]:
np.random.seed(2)
np.random.randint(low = 0, high = 100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations


In [111]:
a = np.arange (5)
a

array([0, 1, 2, 3, 4])

In [112]:
b = ((10 + a) / 100)**2 *1000

In [113]:
b

array([10. , 12.1, 14.4, 16.9, 19.6])

In [114]:
a * b

array([ 0. , 12.1, 28.8, 50.7, 78.4])

## Comparison operations

In [115]:
a

array([0, 1, 2, 3, 4])

In [116]:
a >= 2 

array([False, False,  True,  True,  True])

In [117]:
b = [1,2,2,2,2]
b

[1, 2, 2, 2, 2]

In [118]:
a >= b

array([False, False,  True,  True,  True])

## Summarizing operations

In [119]:
a

array([0, 1, 2, 3, 4])

In [120]:
a.min()

np.int64(0)

In [121]:
a.sum()

np.int64(10)

In [122]:
a.mean()

np.float64(2.0)

In [123]:
n.max()

np.int64(20)

### Next

Linear algebra refresher